"""Create checkin table

Revision ID: 333e3d0d11f0
Revises: 
Create Date: 2023-10-07 15:24:14.173040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333e3d0d11f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Room_number', sa.Integer(), nullable=True),
    sa.Column('time_in', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkin')
    # ### end Alembic commands ###
